version: "3"
services:
  mar-app:
    build:
      context: ./mar-app/
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    container_name: mar-app
    tty: true
    networks:
      - mar-net
  mar-backend:
    build:
      context: ./mar-backend/
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    container_name: mar-backend
    tty: true
    networks:
      - mar-net

networks:
  mar-net:
    external:
      name: mar_network
# docker network create mar_network
# docker-compose up --build
