version: "3"
services:
  mar-app-react:
    build:
      context: ./mar-app/
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    container_name: mar-app-react
    tty: true
    networks:
      - mar-net
  mar-backend-django:
    build:
      context: ./mar-backend/
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    container_name: mar-backend-django
    tty: true
    networks:
      - mar-net
    command: bash -c "python manage.py runserver 0.0.0.0:8000"

networks:
  mar-net:
    external:
      name: mar_network
# docker network create mar_network
# docker-compose up --build
